server:
    port: 8003
#    ssl:
#        key-store: classpath:${server.ssl.store-name}
#        key-store-password: czd102930
#        store-name: linux.jks
https:
    classname: edu.ccmmxj.club.jks
    password: n4r661s3v190r3
    port: 8442
    ssl:
        key-store: classpath:${https.classname}
        key-store-password: ${https.password}
        key-password: ${https.password}
eureka:
    port: 8888
    host: edu.ccmmxj.club
    client:
        serviceUrl:
            defaultZone: http://${eureka.host}:${eureka.port}/eureka/
spring:
    datasource:
        url: jdbc:mysql://edu.ccmmxj.club:3306/shop?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: cmx123456
        driver-class-name: com.mysql.jdbc.Driver
    http:
      multipart:
        max-file-size: 10MB
        max-request-size: 100MB
debug: true

#logging.level.root: warn
#logging.level.root=INFO
#logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernate=ERROR
#logging.path=/home/_xyy_/output/SpringBootDemo/logs
#logging.level.org.springboot.sample=TRACE
logging:
    level:
        root: WARN
        org:
            springframework:
                web: DEBUG
            hibernate: ERROR
            springboot:
                sample: TRACE
        com:
            shop:
                server: INFO
    path: /usr/java/logs
#    config: classpath:logger/logback-spring.xml
#logging.file=demo.log
#
#https:
#  port: 8443
#  ssl:
#    key-store: classpath:${https.ssl.store-name}
#    key-store-password: czd102930
#    key-password: czd102930
#    store-name: linux.jks
#    key-alias: alias
#    key-store-provider: SUN
#    key-store-type: JKS