server:
    port: 8080
eureka:
    port: 8888
    host: localhost
    client:
        serviceUrl:
            defaultZone: http://${eureka.host}:${eureka.port}/eureka/
ribbon:
    eureka:
        enabled: true
https:
    classname: mykeys.jks
    password: cmx123456
    port: 8443
    ssl:
        key-store: classpath:${https.classname}
        key-store-password: ${https.password}
        key-password: ${https.password}
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/shop?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
debug: true

#logging.level.root: warn
#logging.level.root=INFO
#logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernate=ERROR
#logging.path=/home/_xyy_/output/SpringBootDemo/logs
#logging.level.org.springboot.sample=TRACE
logging:
    level:
        root: WARN
        org:
            springframework:
                web: DEBUG
            hibernate: ERROR
            springboot:
                sample: TRACE
        com:
            shop:
                server: DEBUG
    path: D:/code/logs
#    config: classpath:logger/logback-spring.xml
#logging.file=demo.log
#https:
#  port: 8443
#  ssl:
#    key-store: classpath:${https.ssl.store-name}
#    key-store-password: secret
#    key-password: password
#    store-name: springboot.jks